### ISSUE TITLE
change the filed domain name

### ISSUE THREAD

**Issue by redbox2000** [xcir/varnishHostStat#20]
I would like to replace of the domain filed name  character from dot into underscore (json format)

{"#alldata": {"fetch_time": 0.0, "2xx": 1, "req": 1, "5xx": 0, "no_fetch_time": 0.00014328956604003906, "totallen": 2, "4xx": 0, "3xx": 0, "fetch": 0}, "@end-time": 1450969903, "test.test.com": {"fetch_time": 0.0, "2xx": 1, "req": 1, "5xx": 0, "no_fetch_time": 0.00014328956604003906, "totallen": 2, "4xx": 0, "3xx": 0, "fetch": 0}, "@start-time": 1450969899}

{"#alldata": {"fetch_time": 0.0, "2xx": 1, "req": 1, "5xx": 0, "no_fetch_time": 0.00014328956604003906, "totallen": 2, "4xx": 0, "3xx": 0, "fetch": 0}, "@end-time": 1450969903, "test_test_com": {"fetch_time": 0.0, "2xx": 1, "req": 1, "5xx": 0, "no_fetch_time": 0.00014328956604003906, "totallen": 2, "4xx": 0, "3xx": 0, "fetch": 0}, "@start-time": 1450969899}

because the Elasticsearch 2x does not support that  the field name contain dot...
I am not sure...

**Comment by xcir** [comment]
Hi,
I added -R option.
This option can replace field name.

```
#Replace from [.] to [-].
#This pattern is replace from a.example.net to a-example-net
./varnishhoststat.py -R "\./-"
```

For Varnish 4.0/4.1
https://github.com/xcir/varnishHostStat/tree/v0.12-varnish40

For Varnish 3.0
https://github.com/xcir/varnishHostStat/tree/v0.10-varnish30
