### ISSUE TITLE
Make proper releases & integrate RPM specfile

### ISSUE THREAD

**Issue by duritong** [xcir/varnishHostStat#3]
Hi

I just build a RPM spec file to package varnishHostStat (for easier distribution): https://git.immerda.ch/srpm/varnishhoststat/tree/SPECS/varnishhoststat.spec

Actually we could integrate the specfile into this repository, so packaging gets even easier. However, what would needs to be done, is to tag your releases, so we could refer to this version in the specfile for the source rather than the git commit.

If you are interested in getting that in, please make a tag from your latest version and I can then make a PR that merges the specfile into this repository.

Let me know if you have any further questions.

**Comment by xcir** [comment]
Hi,
Nice spec file! Thanks.
I add tags(v0.8_30x)
