### ISSUE TITLE
About fetch size

### ISSUE THREAD

**Issue by redbox-cdn** [xcir/varnishHostStat#32]
Hi 

The totallen value are "No fetch" + "fetch " ?
Is it possible to get "only fetch" contents size?
I would like to check the origin side load.

Best regards.

**Comment by xcir** [comment]
>The totallen value are "No fetch" + "fetch " ?
https://github.com/xcir/varnishHostStat/blob/master/varnishhoststatcore.py#L312-L327
https://github.com/xcir/varnishHostStat/blob/master/varnishhoststatcore.py#L261
"total len" is ReqAcct/PipeAcct's "Total bytes transmitted", not care nofetch / fetch.

>Is it possible to get "only fetch" contents size?
Currently it does not support.

**Comment by xcir** [comment]
Your request (total-fetch-length) added to wishlist.
But, I have other preferred tasks.
p-r welcome! :)
