### ISSUE TITLE
-f Option does not work/

### ISSUE THREAD

**Issue by redbox-cdn** [xcir/varnishHostStat#35]
Hi 

The -f Option does not work. 

> varnishhoststat (master)
> varnishd (varnish-5.2.1)
> Python 2.7.5

`varnishhoststat.py -f TEST`

TEST is req.http.TEST header set in VCL.

Answer is "#n/a" and "#all data"

*in addition,  varnishHostStat latest version is 52.20?
I tried master branch from git hub and then check the version 
`varnishhoststat.py  -V`
Value is varnishhoststat (50.19)

Best regards.

**Comment by xcir** [comment]
Thanks for your report!
fixed this issue.
Please test.

**Comment by redbox-cdn** [comment]
Thanks!  issue has been  solved!
